/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CharactersIndexImport } from './routes/characters/index'
import { Route as CharactersCharacterIdImport } from './routes/characters/$characterId'

// Create/Update Routes

const CharactersIndexRoute = CharactersIndexImport.update({
  path: '/characters/',
  getParentRoute: () => rootRoute,
} as any)

const CharactersCharacterIdRoute = CharactersCharacterIdImport.update({
  path: '/characters/$characterId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/characters/$characterId': {
      id: '/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof CharactersCharacterIdImport
      parentRoute: typeof rootRoute
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  CharactersCharacterIdRoute,
  CharactersIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/characters/$characterId",
        "/characters/"
      ]
    },
    "/characters/$characterId": {
      "filePath": "characters/$characterId.tsx"
    },
    "/characters/": {
      "filePath": "characters/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
